version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/connectdeaf_db
      - SPRING_DATASOURCE_USERNAME=connectdeaf_user
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - connectdeaf-network

  db:
    image: postgres:16
    container_name: connectdeaf_postgres
    environment:
      POSTGRES_USER: connectdeaf_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connectdeaf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - connectdeaf-network

volumes:
  postgres_data:

networks:
  connectdeaf-network:
    driver: bridge
